{
  "hash": "11fbd4a9a48cd9fb44c4b326cd6dea42",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exploring the Simpsons Dataset\"\nsubtitle: \"Final Project Proposal\"\nauthor: \n  - name: \"Daniel Spangler\"\n    affiliations:\n      - name: \"School of Information, University of Arizona\"\ndescription: \"Using the Simpsons dataset to analyze episode rating and character appearances over seasons\"\nformat:\n  html:\n    code-tools: true\n    code-overflow: wrap\n    code-line-numbers: true\n    embed-resources: true\neditor: visual\ncode-annotations: hover\nexecute:\n  warning: false\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidytuesdayR)\n```\n:::\n\n\n## Dataset\n\nA brief description of your dataset including its provenance, dimensions, etc. as well as the reason why you chose this dataset.\n\nMake sure to load the data and use inline code for some of this information.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntuesdata <- tidytuesdayR::tt_load(2025, week = 5)\n\nsimpsons_characters <- tuesdata$simpsons_characters\nsimpsons_episodes <- tuesdata$simpsons_episodes\nsimpsons_locations <- tuesdata$simpsons_locations\nsimpsons_script_lines <- tuesdata$simpsons_script_lines\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(simpsons_characters)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6722    4\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(simpsons_episodes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 151  14\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(simpsons_locations)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4459    3\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(simpsons_script_lines)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 31793    13\n```\n\n\n:::\n:::\n\n\nThe data set that I chose comes from Tidy Tuesday 2025-02-04 and is all about the Simpsons, which is a very popular adult animated sitcom. This data was originally from The Simpsons Dataset on Kaggle. The data set contains four tables each highlighting a different aspect of the show. The tables include characters, episodes, locations, and script lines. The data is very large (with the show having so many seasons), with the character data frame including 6722 rows and script lines data frame containing 31793 rows.\n\nI chose this data set because it is really interesting to look at the success of each different season, and see if that can be attributed to a certain character or location. Any analysis that I can do on movies or TV I always find super interesting, and because of the immense history and quality of this show, I jumped at the chance to do a project on it.\n\nLink to original data set: <https://www.kaggle.com/datasets/prashant111/the-simpsons-dataset>\n\n## Questions\n\nThe two questions you want to answer.\n\n1.  How have the IMDB ratings of the Simpsons episodes changed over time?\n2.  Which Simpsons characters have the most speaking lines each season, and how does this change over time?\n\n## Analysis plan\n\n-   A plan for answering each of the questions including the variables involved, variables to be created (if any), external data to be merged in (if any).\n\nQuestion 1\n\nVariables:\n\n-   season, imdb_rating, us_viewers_in_millions, original_air_year\n\n-   Create categorical variable for era\n\n    -   Classic Era (Seasons 1-8)\n\n    -   Scully Era (Seasons 9-12)\n\n        -   Named after showrunner Mike Scully\n\n    -   Jean SD Era (Seasons 13-19)\n\n        -   Named after Al Jean\n\n    -   Jean HD Era (Seasons 20-Today)\n\n    -   Sourced from <https://nohomers.net/forums/index.php?threads/the-simpsons-eras-division.43685/>\n\nPlanned visualizations:\n\n-   Boxplot per season\n\n-   Bar chart\n\nQuestion 2\n\nVariables:\n\n-   raw_character_text, episode id from script lines data set\n\n-   season from episodes data set\n\nPlanned visualizations:\n\n-   Stacked bar chart showing top 10 characters with most lines\n\n-   Heatmap (also top 10 characters)\n",
    "supporting": [
      "proposal_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}